# fly.toml app configuration file generated for hzt on 2025-03-05T22:23:29+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hzt'
primary_region = 'waw'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
