app = "techbridge-back"

[env]
  JAVA_TOOL_OPTIONS = "-XX:+UseContainerSupport -Dfile.encoding=UTF-8"

[[services]]
  internal_port = 8081
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 81

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
