spring.application.name=HZT

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://c3l5o0rb2a6o4l.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d498stn282tmnq
spring.datasource.username=uctdvu141cmb2l
spring.datasource.password=p84bd40c1fc1eb4be1dab767397ee24e2719d22624ad4728b5db22bf5be674509
spring.datasource.driver-class-name=org.postgresql.Driver

server.port = 8082