# Spring application name
spring.application.name=HZT

# Fly.io PostgreSQL bağlantı URL'si
spring.datasource.url=${DATABASE_URL}  # Fly.io ortam değişkeni kullanılacak

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=novruz1234

# Hibernate JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=${PORT:8080}
